---

- name: 'AlmaLinux - install package epel-release'
  ansible.builtin.package:
    name: 'epel-release'
    state: 'present'
  when:
    - 'ansible_distribution == "AlmaLinux"'
  notify:
    - 'AlmaLinux - install epel-release key'
    - "Run 'dnf makecache'"

- name: 'Flush handlers'
  ansible.builtin.meta: flush_handlers
